title: Ali Jarjis
subtitle: Software Developer
description: Highly motivated software developer with a degree in Computer Science. Experienced as both a web & mobile developer; passionate in coding and cooking.
baseurl: ""
url: "www.ajarjis.com"
author: Ali Jarjis
logo: "/assets/images/logo.png"

social:
  name: Ali Jarjis
  links:
    -https://github.com/AJarjis
    -https://www.linkedin.com/in/ajarjis/

lang: en
timezone: GB

collections:
  works:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ali Jarjis"
  - scope:
      path: ""
    values:
      layout: "default"